#!/bin/bash

SENTRY_CONF_FILE=${SENTRY_CONF_FILE:-/conf/sentry_docker_conf.py}

# export env var for other scripts to work
export SENTRY_CONF=$SENTRY_CONF_FILE
SCRIPTS_DIR=${SENTRY_SCRIPTS_DIR:-/conf}


python $SCRIPTS_DIR/check_db_isalive.py 10 3
if [ "$?" != "0" ]; then
    echo "couldn't establish DB connection. exiting..."
    exit 1
fi

sentry --config=$SENTRY_CONF_FILE upgrade --noinput

exec sentry --config=$SENTRY_CONF_FILE $@

